version: '3'
services:
  app:
    build: ./app
    ports:
     - "8080:8080"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/:/home/node/app/
      - /home/node/app/node_modules
    command: "npm run serve"